cask_args appdir: "/Applications"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"

brew "git-extras"
brew "hh"
brew "imagemagick"
brew "mas"
brew "mongodb"
brew "redis"
brew "mtr"
brew "nmap"
brew "node"
brew "node@8"
brew "nvm"
brew "python3"
brew "watchman"
brew "wget"
brew "wireshark", link: false
brew "yarn"
brew "awscli"
brew "vault"

# Quicklook plugins
brew "qlcolorcode" # Source code with syntax highlighting
brew "qlstephen" # Plain text without or with unknown file extension
brew "qlmarkdown"
brew "quicklook-json" 
brew "qlimagesize"
brew "webpquicklook"
brew "suspicious-package" # Contents of a standard Apple installer package
brew "quicklookase" # Adobe ASE Color Swatches
brew "qlvideo"

cask "java"

cask "santa"

cask "betterzip"

cask "1password"
cask "alfred"
cask "appcleaner"
cask "caprine"
cask "bitbar"
cask "boxer"
cask "docker"
cask "kitematic"
cask "skype"
cask "visual-studio-code"
cask "webstorm"

cask "caption"

cask "charles"
cask "dropbox"
cask "evernote"

cask "atom"
cask "gitup"

cask "adapter"
cask "imageoptim"

# Browsers
cask "google-chrome"
cask "caskroom/versions/google-chrome-canary"
cask "firefox"
cask "opera"
cask "opera-neon"
cask "brave"
cask "torbrowser"

cask "aerial" 

cask "google-backup-and-sync"
cask "graphiql"
cask "hyper"
cask "hyperswitch"
cask "keybase"
cask "keyboard-maestro"
cask "ngrok"
cask "postgres"
cask "pycharm"

cask "adobe-creative-cloud"
cask "sketch"
cask "abstract"

cask "slack"
cask "sourcetree"
cask "transmission"
cask "virtualbox"
cask "vlc"

cask "caskroom/fonts/font-open-sans"
cask "caskroom/fonts/font-roboto"
cask "caskroom/fonts/font-roboto-mono"
cask "caskroom/fonts/font-source-code-pro"
cask "caskroom/versions/dash3"

mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Monosnap", id: 540348655
mas "Moom", id: 419330170
mas "Movist", id: 461788075
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PopClip", id: 445189367
mas "Table Tool", id: 1122008420
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
mas "Amphetamine", id: 937984704
mas "NordVPN", id: 1116599239