cask_args appdir: "/Applications"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"

# Essentials
# ===
brew "git-extras"
brew "hh"
brew "imagemagick"
brew "mas"
brew "mongodb"
brew "redis"
brew "mtr"
brew "nmap"
brew "nvm"
brew "python3"
brew "watchman"
brew "wget"
brew "wireshark", link: false
brew "yarn"
brew "awscli"
brew "vault"
brew "duti"
brew "direnv"

# Quicklook plugins
# ===
brew "qlcolorcode" # Source code with syntax highlighting
brew "qlstephen" # Plain text without or with unknown file extension
brew "qlmarkdown"
brew "quicklook-json"
brew "qlimagesize"
brew "webpquicklook"
brew "suspicious-package" # Contents of a standard Apple installer package
brew "quicklookase" # Adobe ASE Color Swatches
brew "qlvideo"
# TODO: https://github.com/jaketmp/ePub-quicklook

{{{ apps }}}

{{{ fonts }}}
